### ISSUE TITLE
Add option for configuration file

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwiproject-changelog#31]
Add ability to have a configuration file with defaults for some of the command line options. Note that it doesn't make sense for some options such as the previous and current versions.

**Comment by sleberknight** [comment]
A question is whether this option should be mutually exclusive with `-m` and `-O` options. If not, then the categories and label mappings in the configuration file would need to be _merged_ somehow with the command line flags. The `-m` options would override what's in the configuration file, for example if the `-m` option changes the category that a label is mapped to. But I'm not sure how the `-O` order options would actually work, in other words would categories that are not in the config file precede all the categories in the config file? Regardless, the merge code would be complex.

Since the main use case here is to have a "standard" configuration for kiwi projects, right now I think we keep it simple and make these options mutually exclusive. Maybe we even show a warning if both `-m`/`-O` and `-n` (config file) options are provided.

**Comment by sleberknight** [comment]
Something else that just occurred to me is that we should provide some kind of defaulting mechanism for the configuration file, and look for one in a defined order in _well-known locations_.

For example, we look for a `-n`/`--config-file` command line option first. If that isn't found, then we look for a `.kiwi-changelog.yml` in the current working directory. If not found, then look in the parent directory of the working directory. And _maybe_ if that is not found, we look in the current user's home directory.

Using this search order allows local overrides for a specific repository as well as configuration for a _group_ of repositories (for example all _kiwiproject_ repositories), and finally for a default global set of mappings. I'm not sure having a global configuration option makes sense, since it _assumes_ a default set of mappings. Maybe it's fine, e.g., it could like like:

#### `~/.kiwi-changelog.yml`

```yaml
---

categories:

  - name: Improvements
    labels:
      - enhancement

  - name: Bugs
    labels:
      - bug

  - name: Infrastructure
    labels:
      - github_actions

  - name: Assorted
    default: true
     labels:
       - documentation

  - name: "Dependency Updates"
    labels:
      - dependencies

alwaysIncludePRsFrom:
  - "dependabot[bot]"
```

These would work for any repository that uses the default set of GitHub labels, and uses dependabot to update dependencies. And, it uses the _Assorted_ category as the default, which would include issues/PRs with the `documentation` label as well as any other labels that are not mapped.

We might also consider having a way to **disable** looking for any configuration files in the well-known locations, for example if a `--disable-config-file-search` option is provided then we expect there to be `-m` and `-O` arguments.
